security:
    # 1. Especifica cómo se cifran las contraseñas
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # 2. Configura de dónde salen los usuarios
    providers:
        app_user_provider:
            entity:
                class: App\Entity\Usuario # Asegúrate de que este nombre sea exacto
                property: correo           # Aquí le decimos que use el CORREO para el login

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Firewall para el LOGIN
        login:
            pattern: ^/api/login_check # Cambiado para que coincida con el check_path
            stateless: true
            json_login:
                check_path: /api/login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        # Firewall para el resto de la API
        api:
            pattern: ^/api
            stateless: true
            jwt: ~

    access_control:
        - { path: ^/api/login_check, roles: PUBLIC_ACCESS, requires_channel: https }
        - { path: ^/api/register, roles: PUBLIC_ACCESS, requires_channel: https }
        - { path: ^/api,       roles: IS_AUTHENTICATED_FULLY, requires_channel: https }
        - { path: ^/, roles: PUBLIC_ACCESS, requires_channel: https }