services:
  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: bifrost_db
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/var/www/html
    depends_on:
      - database

  apache:
    image: httpd:2.4-alpine
    ports:
      - "8081:80"
    volumes:
      - .:/usr/local/apache2/htdocs/
    command: >
      sh -c "sed -i 's#DocumentRoot \"/usr/local/apache2/htdocs\"#DocumentRoot \"/usr/local/apache2/htdocs/public\"#' /usr/local/apache2/conf/httpd.conf &&
             sed -i 's#<Directory \"/usr/local/apache2/htdocs\">#<Directory \"/usr/local/apache2/htdocs/public\">#' /usr/local/apache2/conf/httpd.conf &&
             sed -i 's#AllowOverride None#AllowOverride All#' /usr/local/apache2/conf/httpd.conf &&
             sed -i 's#^#LoadModule proxy_module modules/mod_proxy.so\\nLoadModule proxy_fcgi_module modules/mod_proxy_fcgi.so\\nLoadModule rewrite_module modules/mod_rewrite.so\\n#' /usr/local/apache2/conf/httpd.conf &&
             echo 'ProxyPassMatch ^/(.*\\.php(/.*)?)$ fcgi://php:9000/var/www/html/public/$$1' >> /usr/local/apache2/conf/httpd.conf &&
             echo 'FallbackResource /index.php' >> /usr/local/apache2/conf/httpd.conf &&
             httpd-foreground"

  mercure:
    image: dunglas/mercure
    ports:
      - "3000:80"
    restart: unless-stopped
    environment:
      SERVER_NAME: ':80'
      MERCURE_PUBLISHER_JWT_KEY: 'tfg_amatista_secure_key_32_chars_'
      MERCURE_SUBSCRIBER_JWT_KEY: 'tfg_amatista_secure_key_32_chars_'
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins http://localhost:8081
      CORS_ALLOWED_ORIGINS: "http://localhost:8081"
    command: /usr/bin/caddy run --config /etc/caddy/dev.Caddyfile
    volumes:
      - mercure_data:/data
      - mercure_config:/config

volumes:
  mercure_data:
  mercure_config:
  db_data: