services:
  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: bifrost_db
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/var/www/html
    depends_on:
      - database

  apache:
    image: httpd:2.4-alpine
    ports:
      - "8081:443" # HTTPS externo 8081 mapea al 443 interno
    volumes:
      - .:/var/www/html
      - ./server.crt:/usr/local/apache2/conf/server.crt
      - ./server.key:/usr/local/apache2/conf/server.key
      - ./my-httpd-ssl.conf:/usr/local/apache2/conf/httpd.conf 
    depends_on:
      - php

  mercure:
    image: dunglas/mercure
    ports:
      - "3000:80"
    restart: unless-stopped
    environment:
      SERVER_NAME: ':80'
      MERCURE_PUBLISHER_JWT_KEY: 'tfg_amatista_secure_key_32_chars_'
      MERCURE_SUBSCRIBER_JWT_KEY: 'tfg_amatista_secure_key_32_chars_'
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins https://localhost:8081
      CORS_ALLOWED_ORIGINS: "https://localhost:8081"
    command: /usr/bin/caddy run --config /etc/caddy/dev.Caddyfile
    volumes:
      - mercure_data:/data
      - mercure_config:/config

volumes:
  mercure_data:
  mercure_config:
  db_data: